name: gentle
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - anytree==2.13.0
      - boto3==1.42.32
      - botocore==1.42.32
      - certifi==2026.1.4
      - click==8.3.1
      - cmeel-boost==1.83.0
      - cmeel-tinyxml==2.6.2.3
      - cmeel-urdfdom==3.1.1.1
      - coloredlogs==15.0.1
      - dex-retargeting==0.4.6
      - eigenpy==3.5.1
      - einops==0.8.1
      - flaky==3.8.1
      - flatbuffers==25.12.19
      - flatdict==4.0.1
      - gymnasium==1.2.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hidapi==0.14.0.post2
      - hpp-fcl==2.4.4
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio-ffmpeg==0.6.0
      - iniconfig==2.3.0
      - ipywidgets==8.1.5
      - isaacsim==4.5.0.0
      - isaacsim-app==4.5.0.0
      - isaacsim-asset==4.5.0.0
      - isaacsim-benchmark==4.5.0.0
      - isaacsim-code-editor==4.5.0.0
      - isaacsim-core==4.5.0.0
      - isaacsim-cortex==4.5.0.0
      - isaacsim-example==4.5.0.0
      - isaacsim-extscache-kit==4.5.0.0
      - isaacsim-extscache-kit-sdk==4.5.0.0
      - isaacsim-extscache-physics==4.5.0.0
      - isaacsim-gui==4.5.0.0
      - isaacsim-kernel==4.5.0.0
      - isaacsim-replicator==4.5.0.0
      - isaacsim-rl==4.5.0.0
      - isaacsim-robot==4.5.0.0
      - isaacsim-robot-motion==4.5.0.0
      - isaacsim-robot-setup==4.5.0.0
      - isaacsim-ros1==4.5.0.0
      - isaacsim-ros2==4.5.0.0
      - isaacsim-sensor==4.5.0.0
      - isaacsim-storage==4.5.0.0
      - isaacsim-template==4.5.0.0
      - isaacsim-test==4.5.0.0
      - isaacsim-utils==4.5.0.0
      - jmespath==1.0.1
      - joblib==1.5.3
      - junitparser==4.0.2
      - jupyterlab-widgets==3.0.16
      - llvmlite==0.46.0
      - loop-rate-limiters==1.2.0
      - moviepy==2.2.1
      - nlopt==2.7.1
      - numba==0.63.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - omniverse-kit==106.5.0.162521
      - onnx==1.20.1
      - onnxruntime==1.23.2
      - osqp==0.6.7.post3
      - pexpect==4.9.0
      - pillow==11.2.1
      - pin==2.7.0
      - pin-pink==3.1.0
      - pluggy==1.6.0
      - prettytable==3.3.0
      - proglog==0.1.12
      - protobuf==6.33.4
      - ptyprocess==0.7.0
      - pyglet==1.5.31
      - pyperclip==1.11.0
      - pytest==9.0.2
      - pytest-mock==3.15.1
      - pytransform3d==3.14.4
      - qdldl==0.1.7.post5
      - qpsolvers==4.8.2
      - quadprog==0.1.13
      - regex==2026.1.15
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - starlette==0.45.3
      - sympy==1.14.0
      - tensordict==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - torch==2.7.0+cu128
      - torchrl==0.7.2
      - torchvision==0.22.0+cu128
      - transformers==4.57.6
      - trimesh==4.11.1
      - triton==3.3.0
      - wandb==0.24.0
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - zipp==3.23.0
prefix: /home/liwei/F/003LinuxSoftwares/miniconda3/envs/gentle
